import XCTest
import GRDB
@testable import LariatDB

/// Phase C2 — proves the native `SchemaMigrator` builds a fresh database whose
/// schema is identical to one built by the web app's `lib/db.ts initSchema()`.
/// The baseline fixtures are generated by `scripts/dump-fresh-schema.mjs`
/// (see each fixture header for the regen command). If a legitimate web schema
/// change lands, regenerate the fixtures and re-run.
final class SchemaMigratorTests: XCTestCase {

    // MARK: - Fixture loading

    private func fixtureLines(_ name: String) throws -> [String] {
        guard let url = Bundle.module.url(forResource: name, withExtension: nil, subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: name, withExtension: nil)
        else {
            XCTFail("missing fixture \(name)")
            throw Fixture.missing
        }
        let text = try String(contentsOf: url, encoding: .utf8)
        return text
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty && !$0.hasPrefix("--") }
    }

    private enum Fixture: Error { case missing }

    /// A fresh in-memory database migrated by the native `SchemaMigrator`.
    private func freshMigratedDb() throws -> DatabaseQueue {
        let dbq = try DatabaseQueue()
        try SchemaMigrator().migrate(dbq)
        return dbq
    }

    // MARK: - C2 parity

    func testFreshSchemaMatchesWebBaseline() throws {
        let expected = try fixtureLines("web_schema_baseline.sql")
        let dbq = try freshMigratedDb()
        let actual = try dbq.read { try SchemaDump.normalizedLines($0) }

        let expectedSet = Set(expected)
        let actualSet = Set(actual)

        let missing = expectedSet.subtracting(actualSet).sorted()   // in web, not native
        let extra = actualSet.subtracting(expectedSet).sorted()     // in native, not web

        XCTAssertTrue(
            missing.isEmpty,
            "schema objects the web has but native did not build (\(missing.count)):\n"
                + missing.joined(separator: "\n")
        )
        XCTAssertTrue(
            extra.isEmpty,
            "schema objects native built that the web does not have (\(extra.count)):\n"
                + extra.joined(separator: "\n")
        )
    }

    func testFreshSeedMatchesWebBaseline() throws {
        let expected = try fixtureLines("web_seed_baseline.txt")
        let dbq = try freshMigratedDb()
        let actual = try dbq.read { try SchemaDump.seedLines($0) }
        XCTAssertEqual(Set(actual), Set(expected),
            "seed rows diverge from the web baseline")
    }

    // MARK: - Version stamping

    func testMigrateStampsExpectedUserVersion() throws {
        let dbq = try freshMigratedDb()
        let version = try dbq.read { try SchemaMigrator.currentVersion($0) }
        XCTAssertEqual(version, SchemaMigrator.expectedVersion)
        XCTAssertEqual(SchemaMigrator.expectedVersion, SchemaMigrator.migrationIdentifiers.count)
    }

    func testReplaysWebSchemaMigrationsMarker() throws {
        // The web stamps SCHEMA_VERSION into its own schema_migrations table
        // (schemaVersionMarker step); native replays it verbatim.
        let dbq = try freshMigratedDb()
        let webVersion = try dbq.read { try SchemaMigrator.webSchemaMigrationsVersion($0) }
        XCTAssertEqual(webVersion, SchemaMigrator.webSchemaVersion)
    }

    // MARK: - Idempotency + already-migrated no-op

    func testMigrateIsIdempotent() throws {
        let dbq = try DatabaseQueue()
        let migrator = SchemaMigrator()
        try migrator.migrate(dbq)
        let first = try dbq.read { try SchemaDump.normalizedLines($0) }
        // Re-running must not error and must not change the schema.
        try migrator.migrate(dbq)
        let second = try dbq.read { try SchemaDump.normalizedLines($0) }
        XCTAssertEqual(first, second)
    }

    func testMigrateAgainstAlreadyMigratedWebDbIsNoop() throws {
        // Reconstruct a web-built DB from the committed full dump, then run the
        // native migrator over it: every step is `IF NOT EXISTS`/re-entrant, so
        // the schema must be unchanged and no error thrown.
        let webSql = try String(
            contentsOf: XCTUnwrap(
                Bundle.module.url(forResource: "web_full_dump", withExtension: "sql", subdirectory: "Fixtures")
                    ?? Bundle.module.url(forResource: "web_full_dump", withExtension: "sql")
            ),
            encoding: .utf8
        )
        let dbq = try DatabaseQueue()
        // GRDB executes the whole multi-statement dump (tables → indexes →
        // seed INSERTs, `--` comments and all) in one call — no hand-splitting.
        try dbq.write { try $0.execute(sql: webSql) }
        let before = try dbq.read { try SchemaDump.normalizedLines($0) }
        try SchemaMigrator().migrate(dbq)
        let after = try dbq.read { try SchemaDump.normalizedLines($0) }
        XCTAssertEqual(before, after, "native migrate over a web-built DB changed the schema")
    }
}
