-- Generated by scripts/dump-fresh-schema.mjs (mode: executable).
-- Source of truth: lib/db.ts initSchema() replayed against a fresh temp DB.
-- Regenerate with:
--   node scripts/dump-fresh-schema.mjs --executable > LariatNative/Sources/LariatDB/Resources/frozen_schema.sql
-- Comment lines (--) and blank lines are ignored by the Swift parity tests.

CREATE TABLE IF NOT EXISTS line_check_entries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      station_id TEXT NOT NULL,
      item TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('pass','fail','na')),
      par TEXT,
      have TEXT,
      need TEXT,
      note TEXT,
      cook_id TEXT,
      -- F15 (FDA §3-301.11): NULL = item doesn't touch RTE food;
      -- 0 = glove-change required but not yet attested;
      -- 1 = cook has attested fresh gloves for this line-check row.
      glove_change_attested INTEGER,
      created_at TEXT DEFAULT (datetime('now')),
      location_id TEXT DEFAULT 'default'
    );
CREATE TABLE IF NOT EXISTS station_signoffs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      station_id TEXT NOT NULL,
      cook_id TEXT NOT NULL,
      signoff_type TEXT NOT NULL DEFAULT 'self',
      created_at TEXT DEFAULT (datetime('now')),
      location_id TEXT DEFAULT 'default'
    );
CREATE TABLE IF NOT EXISTS eighty_six (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      station_id TEXT,
      item TEXT NOT NULL,
      kind TEXT DEFAULT 'item',
      reason TEXT,
      quantity TEXT,
      cook_id TEXT,
      resolved_at TEXT,
      resolved_by TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      location_id TEXT DEFAULT 'default'
    );
CREATE TABLE IF NOT EXISTS inventory_updates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      station_id TEXT,
      item TEXT NOT NULL,
      master_id TEXT,
      delta TEXT,
      direction TEXT,
      note TEXT,
      cook_id TEXT,
      sync_source_host TEXT,
      sync_source_started_at TEXT,
      sync_source_pk TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      location_id TEXT DEFAULT 'default'
    , receiving_log_id INTEGER REFERENCES receiving_log(id));
CREATE TABLE IF NOT EXISTS inventory_counts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      count_date TEXT NOT NULL,
      label TEXT,
      opened_at TEXT DEFAULT (datetime('now')),
      closed_at TEXT,
      cook_id TEXT,
      location_id TEXT NOT NULL DEFAULT 'default'
    );
CREATE TABLE IF NOT EXISTS inventory_count_lines (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      count_id INTEGER NOT NULL REFERENCES inventory_counts(id) ON DELETE CASCADE,
      vendor TEXT,
      ingredient TEXT NOT NULL,
      sku TEXT NOT NULL DEFAULT '',
      on_hand_qty REAL,
      unit TEXT,
      par_qty REAL,
      par_unit TEXT,
      note TEXT,
      counted_by TEXT,
      counted_at TEXT DEFAULT (datetime('now')),
      location_id TEXT NOT NULL DEFAULT 'default',
      UNIQUE(count_id, ingredient, sku)
    );
CREATE TABLE IF NOT EXISTS inventory_par (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      vendor TEXT,
      ingredient TEXT NOT NULL,
      sku TEXT NOT NULL DEFAULT '',
      par_qty REAL,
      par_unit TEXT,
      pack_size TEXT,
      pack_unit TEXT,
      category TEXT,
      note TEXT,
      location_id TEXT NOT NULL DEFAULT 'default',
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(location_id, ingredient, sku)
    );
CREATE TABLE IF NOT EXISTS prep_tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      station_id TEXT,
      task TEXT NOT NULL,
      qty TEXT,
      recipe_slug TEXT,
      notes TEXT,
      priority INTEGER DEFAULT 0,
      assigned_cook_id TEXT,
      status TEXT NOT NULL DEFAULT 'todo'
        CHECK(status IN ('todo','in_progress','done','skipped')),
      started_at TEXT,
      done_at TEXT,
      done_by TEXT,
      source TEXT DEFAULT 'manual',
      source_ref TEXT,
      sort_order INTEGER DEFAULT 0,
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS prep_par (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      station_id TEXT NOT NULL DEFAULT '',
      recipe_slug TEXT NOT NULL DEFAULT '',
      ingredient TEXT NOT NULL DEFAULT '',
      target_qty REAL,
      unit TEXT,
      sort_order INTEGER DEFAULT 0,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(location_id, station_id, recipe_slug, ingredient),
      CHECK (recipe_slug <> '' OR ingredient <> '')
    );
CREATE TABLE IF NOT EXISTS reservations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      party_name TEXT NOT NULL,
      party_size INTEGER NOT NULL,
      reservation_at TEXT NOT NULL,           -- 'YYYY-MM-DD HH:MM' local
      status TEXT NOT NULL DEFAULT 'booked'
        CHECK(status IN ('booked','seated','completed','cancelled','no_show')),
      table_id TEXT,                          -- soft FK to tables.id once that exists
      phone TEXT,
      email TEXT,
      notes TEXT,
      source TEXT DEFAULT 'manual',           -- 'manual', 'opentable', 'phone', etc.
      source_ref TEXT,
      seated_at TEXT,
      completed_at TEXT,
      cook_id TEXT,                           -- whoever booked or last touched it
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS waitlist_parties (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      party_name TEXT NOT NULL,
      party_size INTEGER NOT NULL,
      joined_at TEXT NOT NULL DEFAULT (datetime('now')),
      status TEXT NOT NULL DEFAULT 'waiting'
        CHECK(status IN ('waiting','seated','left')),
      seated_at TEXT,
      left_at TEXT,
      phone TEXT,
      notes TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS dining_tables (
      id TEXT NOT NULL,                     -- e.g. 'T1', 'T2', 'BAR-3'
      name TEXT NOT NULL,                   -- display label, e.g. 'Window 4'
      capacity INTEGER NOT NULL DEFAULT 2,
      x REAL NOT NULL DEFAULT 0,
      y REAL NOT NULL DEFAULT 0,
      w REAL NOT NULL DEFAULT 1,
      h REAL NOT NULL DEFAULT 1,
      status TEXT NOT NULL DEFAULT 'open'
        CHECK(status IN ('open','seated','dirty','closed')),
      notes TEXT,
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      PRIMARY KEY (location_id, id)
    );
CREATE TABLE IF NOT EXISTS locations (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      created_at TEXT DEFAULT (datetime('now'))
    , capacity INTEGER, tax_rate REAL DEFAULT 0.0675, service_fee_pct REAL DEFAULT 20, phone TEXT, address TEXT);
CREATE TABLE IF NOT EXISTS service_hours (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      day_of_week INTEGER NOT NULL,
      opens_at TEXT,
      closes_at TEXT,
      service_label TEXT,
      notes TEXT,
      active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now')), archived_at TEXT,
      UNIQUE(location_id, day_of_week, service_label)
    );
CREATE TABLE IF NOT EXISTS preshift_notes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      shift_date TEXT NOT NULL,
      service_label TEXT,
      body TEXT NOT NULL,
      author_cook_id TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(location_id, shift_date, service_label)
    );
CREATE TABLE IF NOT EXISTS vendor_prices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ingredient TEXT NOT NULL,
      vendor TEXT,
      sku TEXT,
      pack_size REAL,
      pack_unit TEXT,
      pack_price REAL,
      unit_price REAL,
      category TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now'))
    , yield_pct REAL, actual_received_lb REAL, reconciled_unit_price REAL, map_status TEXT, master_id TEXT);
CREATE TABLE IF NOT EXISTS vendor_prices_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      run_id INTEGER,
      source_vendor_price_id INTEGER,
      ingredient TEXT NOT NULL,
      vendor TEXT,
      sku TEXT,
      pack_size REAL,
      pack_unit TEXT,
      pack_price REAL,
      unit_price REAL,
      category TEXT,
      yield_pct REAL,
      actual_received_lb REAL,
      reconciled_unit_price REAL,
      master_id TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT,
      snapshot_at TEXT DEFAULT (datetime('now','subsec')),
      snapshot_reason TEXT
    );
CREATE TABLE IF NOT EXISTS recipe_costs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      recipe_id TEXT NOT NULL,
      recipe_name TEXT,
      category TEXT,
      yield REAL,
      yield_unit TEXT,
      batch_cost REAL,
      cost_per_yield_unit REAL,
      costed_lines INTEGER,
      total_lines INTEGER,
      interpretations INTEGER,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now')),
      UNIQUE(location_id, recipe_id)
    );
CREATE TABLE IF NOT EXISTS recipe_photos (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      recipe_slug TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      original_name TEXT NOT NULL,
      stored_path TEXT NOT NULL,
      mime TEXT NOT NULL,
      size_bytes INTEGER NOT NULL,
      caption TEXT,
      uploaded_by_cook_id TEXT,
      uploaded_at TEXT NOT NULL DEFAULT (datetime('now')),
      deleted_at TEXT
    , is_hero INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS margin_snapshots (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      item_name TEXT NOT NULL,
      net_sales REAL,
      cost_per_unit REAL,
      margin_pct REAL,
      popularity REAL,
      quadrant TEXT,
      snapshot_at TEXT DEFAULT (datetime('now')),
      location_id TEXT DEFAULT 'default'
    );
CREATE TABLE IF NOT EXISTS dish_coverage_snapshots (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      total_dishes INTEGER,
      covered_dishes INTEGER,
      coverage_pct REAL,
      uncovered_dishes TEXT,
      created_by TEXT,
      snapshot_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS accounting_variance (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      period_start TEXT,
      period_end TEXT,
      theoretical_cogs REAL,
      actual_cogs REAL,
      variance_amount REAL,
      variance_pct REAL,
      snapshot_at TEXT DEFAULT (datetime('now')),
      location_id TEXT DEFAULT 'default'
    , actual_cogs_breakdown_json TEXT);
CREATE TABLE IF NOT EXISTS bom_lines (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      recipe_id TEXT NOT NULL,
      ingredient TEXT,
      qty REAL,
      unit TEXT,
      sub_recipe TEXT,
      vendor_ingredient TEXT,
      map_status TEXT,
      vendor TEXT,
      pack_price REAL,
      pack_size REAL,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now'))
    , yield_pct REAL, loss_factor REAL, master_id TEXT);
CREATE TABLE IF NOT EXISTS ingredient_maps (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      recipe_ingredient TEXT NOT NULL,
      vendor_ingredient TEXT,
      status TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS ingredient_masters (
      master_id           TEXT PRIMARY KEY,  -- slug: "ketchup_heinz_1gal"
      canonical_name      TEXT NOT NULL,
      category            TEXT,
      preferred_vendor    TEXT,
      quality_locked      INTEGER NOT NULL DEFAULT 0,
      quality_lock_reason TEXT,
      last_reviewed       TEXT
    );
CREATE TABLE IF NOT EXISTS ingredient_densities (
      ingredient_key TEXT PRIMARY KEY,
      g_per_ml REAL NOT NULL,
      source TEXT CHECK (source IS NULL OR source IN ('seed', 'measured', 'vendor')),
      updated_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS ingredient_unit_weights (
      ingredient_key TEXT NOT NULL,
      unit           TEXT NOT NULL,        -- canonical count unit (post-normalize_unit)
      g_per_unit     REAL NOT NULL,        -- grams per 1 of the count unit above
      source         TEXT CHECK (source IS NULL OR source IN ('seed', 'measured', 'vendor')),
      updated_at     TEXT DEFAULT (datetime('now')),
      PRIMARY KEY (ingredient_key, unit)
    );
CREATE TABLE IF NOT EXISTS vendor_catch_weights (
      vendor        TEXT NOT NULL,
      sku           TEXT NOT NULL,
      catalog_wt_lb REAL NOT NULL,
      tare_lb       REAL,
      source        TEXT,
      updated_at    TEXT DEFAULT (datetime('now')),
      PRIMARY KEY (vendor, sku)
    );
CREATE TABLE IF NOT EXISTS pack_size_changes (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      vendor       TEXT NOT NULL,
      sku          TEXT NOT NULL,
      prev_pack    TEXT,  -- e.g. "6x#10"
      new_pack     TEXT,
      prev_price   REAL,
      new_price    REAL,
      detected_at  TEXT DEFAULT (datetime('now')),
      acknowledged INTEGER DEFAULT 0
    );
CREATE TABLE IF NOT EXISTS ingredient_yields (
      ingredient_key TEXT PRIMARY KEY,     -- same normalized form as ingredient_densities
      yield_pct      REAL NOT NULL,        -- fraction 0..1 (e.g. 0.85 for 85% trim yield)
      loss_factor    REAL,                 -- cooking-shrinkage fraction 0..1; NULL if not applicable
      source         TEXT NOT NULL CHECK (source IN ('book_of_yields', 'lariat_measured', 'seed')),
      notes          TEXT,                 -- provenance / edge-case detail
      updated_at     TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS ingest_runs (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      kind         TEXT NOT NULL,          -- 'costing' | 'analytics' | 'unified' | 'toast' | ...
      started_at   TEXT NOT NULL,          -- ISO 8601 via datetime('now','subsec')
      finished_at  TEXT,                   -- NULL while running
      rows_in      INTEGER,
      rows_out     INTEGER,
      status       TEXT                    -- 'ok' | 'partial' | 'failed' | 'running'
    );
CREATE TABLE IF NOT EXISTS order_guide_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ingredient TEXT NOT NULL,
      base_qty REAL,
      unit TEXT,
      vendor TEXT,
      unit_price REAL,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now')),
      -- 1 = row holds a recipe-derived placeholder cost (no real vendor
      -- invoice yet) and MUST be ignored by the costing bridge. Backfill
      -- script scripts/flag-placeholder-order-guide.mjs stamps it for
      -- known bad rows; ingest pipelines never set it to 1.
      is_placeholder INTEGER DEFAULT 0
    );
CREATE TABLE IF NOT EXISTS sales_lines (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      period_label TEXT,
      item_name TEXT NOT NULL,
      quantity_sold REAL,
      net_sales REAL,
      source TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now'))
    , service_date TEXT, service_period TEXT);
CREATE TABLE IF NOT EXISTS dish_components (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      dish_name TEXT NOT NULL,
      component_type TEXT NOT NULL DEFAULT 'recipe'
        CHECK(component_type IN ('recipe', 'vendor_item')),
      recipe_slug TEXT,
      vendor_ingredient TEXT,
      qty_per_serving REAL NOT NULL,
      unit TEXT NOT NULL,
      notes TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      CHECK (
        (component_type = 'recipe' AND recipe_slug IS NOT NULL AND vendor_ingredient IS NULL) OR
        (component_type = 'vendor_item' AND vendor_ingredient IS NOT NULL AND recipe_slug IS NULL)
      )
    );
CREATE TABLE IF NOT EXISTS spend_monthly (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      month TEXT NOT NULL,
      shamrock_total_spend REAL,
      source TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS beo_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      event_date TEXT,
      event_time TEXT,
      contact_name TEXT,
      guest_count INTEGER,
      notes TEXT,
      status TEXT DEFAULT 'planned',
      tax_rate REAL DEFAULT 0.0675,
      service_fee_pct REAL DEFAULT 20,
      min_spend REAL,
      share_token TEXT,
      share_expires_at TEXT,
      share_revoked_at TEXT,
      location_id TEXT DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS beo_line_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id INTEGER NOT NULL,
      sort_order INTEGER DEFAULT 0,
      item_name TEXT NOT NULL,
      category TEXT,
      unit_cost REAL NOT NULL DEFAULT 0,
      quantity REAL NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now')), prep_notes TEXT, secondary_prep_notes TEXT, order_items_notes TEXT, order_time TEXT, group_note TEXT, course_id INTEGER REFERENCES beo_courses(id) ON DELETE SET NULL,
      FOREIGN KEY (event_id) REFERENCES beo_events(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS beo_prep_tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id INTEGER NOT NULL,
      task TEXT NOT NULL,
      due_date TEXT,
      done INTEGER DEFAULT 0,
      sort_order INTEGER DEFAULT 0,
      location_id TEXT DEFAULT 'default',
      FOREIGN KEY (event_id) REFERENCES beo_events(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS beo_prep_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      client TEXT,
      event_date TEXT,            -- ISO YYYY-MM-DD
      event_file TEXT,            -- source xlsx filename if known
      type TEXT,                  -- 'Main Item' | 'Secondary Prep' | 'Special Sauce' | …
      item TEXT NOT NULL,
      amount_qty TEXT,            -- numeric or descriptive (kept as text)
      prep_day TEXT,
      pre_prep_notes TEXT,
      plating_notes TEXT,
      source TEXT NOT NULL,       -- e.g. 'master_workbook_2026-04-18'
      imported_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS equipment (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      make_model TEXT,
      serial_number TEXT,
      purchase_date TEXT,
      warranty_expiration TEXT,
      purchase_cost REAL,
      status TEXT DEFAULT 'active',
      location_id TEXT DEFAULT 'default'
    , model_number TEXT, vendor TEXT, vendor_order_ref TEXT, manual_path TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS equipment_maintenance (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      equipment_id INTEGER NOT NULL,
      service_date TEXT NOT NULL,
      type TEXT NOT NULL,
      cost REAL,
      notes TEXT,
      receipt_reference TEXT,
      cook_id TEXT,
      location_id TEXT DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS equipment_parts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      equipment_id INTEGER NOT NULL,
      part_number TEXT NOT NULL,
      description TEXT,
      vendor TEXT,
      unit_price REAL,
      qty_on_hand REAL,
      last_ordered TEXT,
      last_order_ref TEXT,
      notes TEXT,
      location_id TEXT DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS equipment_maintenance_schedule (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      equipment_id INTEGER NOT NULL,
      task TEXT NOT NULL,
      frequency TEXT NOT NULL,
      last_done TEXT,
      next_due TEXT,
      notes TEXT,
      location_id TEXT DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS gold_stars (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      cook_name TEXT NOT NULL,
      reason TEXT NOT NULL,
      stars INTEGER DEFAULT 1,
      awarded_date TEXT DEFAULT (date('now')),
      location_id TEXT DEFAULT 'default',
      created_at TEXT DEFAULT (datetime('now')),
      deleted_at TEXT,
      deleted_by TEXT
    );
CREATE TABLE IF NOT EXISTS temp_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      point_id TEXT NOT NULL,
      reading_f REAL NOT NULL,
      required_min_f REAL,
      required_max_f REAL,
      corrective_action TEXT,
      cook_id TEXT,
      -- Bundle G: optional thermometer id linking the reading to a
      -- probe calibration record (see thermometer_calibrations). Null
      -- means "no probe recorded" — reading is still persisted.
      probe_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS toast_sales_daily (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      net_sales REAL,
      orders INTEGER,
      guests INTEGER,
      comparison_group INTEGER NOT NULL,
      date_range TEXT,
      source TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now')),
      UNIQUE(shift_date, comparison_group, location_id)
    );
CREATE TABLE IF NOT EXISTS toast_sales_dow (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      day_of_week TEXT NOT NULL,
      net_sales REAL,
      orders INTEGER,
      guests INTEGER,
      comparison_group INTEGER NOT NULL,
      date_range TEXT,
      source TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now')),
      UNIQUE(day_of_week, comparison_group, location_id)
    );
CREATE TABLE IF NOT EXISTS toast_sales_hour (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hour_24 INTEGER NOT NULL,
      label TEXT NOT NULL,
      net_sales REAL,
      orders INTEGER,
      guests INTEGER,
      comparison_group INTEGER NOT NULL,
      date_range TEXT,
      source TEXT,
      location_id TEXT DEFAULT 'default',
      imported_at TEXT DEFAULT (datetime('now')),
      UNIQUE(hour_24, comparison_group, location_id)
    );
CREATE TABLE IF NOT EXISTS toast_subscription_invoices (
      invoice_no    TEXT NOT NULL,
      invoice_date  TEXT NOT NULL,                    -- YYYY-MM-DD
      invoice_total REAL NOT NULL,
      line_count    INTEGER NOT NULL,
      source_pdf    TEXT,
      location_id   TEXT NOT NULL DEFAULT 'default',
      ingested_at   TEXT NOT NULL DEFAULT (datetime('now','subsec')),
      PRIMARY KEY (location_id, invoice_no)
    );
CREATE TABLE IF NOT EXISTS toast_subscription_invoice_lines (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_no   TEXT NOT NULL,
      invoice_date TEXT NOT NULL,                     -- denormalized for fast year/month rollups
      line_seq     INTEGER NOT NULL,                  -- 1-based order within the invoice
      item         TEXT NOT NULL,
      qty          INTEGER NOT NULL,                  -- can be negative (credit lines)
      rate         REAL NOT NULL,
      amount       REAL NOT NULL,                     -- can be negative (credit lines)
      location_id  TEXT NOT NULL DEFAULT 'default',
      UNIQUE(location_id, invoice_no, line_seq)
    );
CREATE TABLE IF NOT EXISTS cloud_bridge_outbox (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      table_name    TEXT NOT NULL,
      location_id   TEXT NOT NULL DEFAULT 'default',
      rows_json     TEXT NOT NULL,
      attempts      INTEGER NOT NULL DEFAULT 0,
      last_error    TEXT,
      dead_letter   INTEGER NOT NULL DEFAULT 0,
      enqueued_at   TEXT NOT NULL DEFAULT (datetime('now')),
      claimed_at    TEXT,
      -- Audit H6 (2026-05-14): per-process claim owner. Set by claim()
      -- to lib/cloudBridgeQueue::OWNER (a UUID generated at module
      -- load). releaseAllClaimedRows() filters by this so a graceful
      -- shutdown only releases rows THIS process is holding — never
      -- yanks an in-flight claim out from under another drainer
      -- running in a different process (e.g. the standalone
      -- scripts/cloud-bridge-drainer.mjs alongside the in-process
      -- drainer from instrumentation.ts). sweepStaleClaims still
      -- ignores ownership (it's a time-based recovery for crashed
      -- holders, where the original owner is by definition gone).
      claim_owner   TEXT
    );
CREATE TABLE IF NOT EXISTS cooling_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      item TEXT NOT NULL,
      station_id TEXT,
      started_at TEXT NOT NULL,
      start_reading_f REAL,
      stage1_at TEXT,
      stage1_reading_f REAL,
      stage2_at TEXT,
      stage2_reading_f REAL,
      status TEXT NOT NULL DEFAULT 'in_progress'
        CHECK(status IN ('in_progress','ok','breach')),
      breach_reason TEXT,
      corrective_action TEXT,
      cook_id TEXT,
      closed_by_cook_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS date_marks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      item TEXT NOT NULL,
      batch_ref TEXT,
      prepared_on TEXT NOT NULL,
      discard_on TEXT NOT NULL,
      discarded_at TEXT,
      discarded_by_cook_id TEXT,
      discard_reason TEXT,
      cook_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS receiving_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      vendor TEXT NOT NULL,
      invoice_ref TEXT,
      category TEXT NOT NULL,
      item TEXT,
      vendor_sku TEXT,
      master_id TEXT,
      match_status TEXT DEFAULT 'not_attempted',
      match_reason TEXT,
      reading_f REAL,
      required_max_f REAL,
      package_ok INTEGER,               -- 1 = intact, 0 = compromised, NULL = unrecorded (legacy)
      expiration_date TEXT,             -- YYYY-MM-DD; NULL when not printed on the case
      status TEXT NOT NULL
        CHECK(status IN ('accepted','rejected','accepted_with_note')),
      rejection_reason TEXT,
      shellstock_tag_ref TEXT,
      cook_id TEXT,
      sync_source_host TEXT,
      sync_source_started_at TEXT,
      sync_source_pk TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    , received_qty REAL, received_unit TEXT);
CREATE TABLE IF NOT EXISTS sanitizer_checks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      station_id TEXT,
      point_label TEXT NOT NULL,
      chemistry TEXT NOT NULL
        CHECK(chemistry IN ('chlorine','quat','iodine','other')),
      concentration_ppm REAL NOT NULL,
      required_min_ppm REAL,
      required_max_ppm REAL,
      water_temp_f REAL,
      status TEXT NOT NULL CHECK(status IN ('ok','low','high')),
      corrective_action TEXT,
      cook_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS sick_worker_reports (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      reported_by_pic_id TEXT,
      symptoms TEXT NOT NULL,
      diagnosed_illness TEXT,
      action TEXT NOT NULL
        CHECK(action IN ('excluded','restricted','monitor','none')),
      started_at TEXT NOT NULL,
      return_at TEXT,
      clearance_source TEXT,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS sick_note_documents (
      id                INTEGER PRIMARY KEY AUTOINCREMENT,
      report_id         INTEGER NOT NULL,
      location_id       TEXT    NOT NULL,
      file_path         TEXT    NOT NULL,
      kind              TEXT    NOT NULL,
      original_filename TEXT,
      uploaded_by       TEXT,
      uploaded_at       TEXT    NOT NULL
    );
CREATE TABLE IF NOT EXISTS staff_certifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      cert_type TEXT NOT NULL
        CHECK(cert_type IN ('cfpm','food_handler','tips','allergen','other')),
      cert_label TEXT NOT NULL,
      issuer TEXT,
      cert_number TEXT,
      issued_on TEXT,
      expires_on TEXT,
      document_path TEXT,
      active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    , archived_at TEXT);
CREATE TABLE IF NOT EXISTS shift_pic (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      shift_slot TEXT NOT NULL
        CHECK(shift_slot IN ('open','mid','close','all_day')),
      cook_id TEXT NOT NULL,
      cfpm_cert_id INTEGER,
      started_at TEXT NOT NULL,
      ended_at TEXT,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (cfpm_cert_id) REFERENCES staff_certifications(id) ON DELETE SET NULL
    );
CREATE TABLE IF NOT EXISTS cleaning_schedule (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      area TEXT NOT NULL,
      task TEXT NOT NULL,
      frequency TEXT NOT NULL,
      last_done TEXT,
      next_due TEXT,
      notes TEXT,
      active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now'))
    , archived_at TEXT);
CREATE TABLE IF NOT EXISTS cleaning_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      schedule_id INTEGER,
      area TEXT NOT NULL,
      task TEXT NOT NULL,
      completed_at TEXT NOT NULL,
      cook_id TEXT,
      verified_by_cook_id TEXT,
      notes TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (schedule_id) REFERENCES cleaning_schedule(id) ON DELETE SET NULL
    );
CREATE TABLE IF NOT EXISTS pest_control_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      entry_type TEXT NOT NULL
        CHECK(entry_type IN ('service_visit','sighting','trap_check')),
      vendor TEXT,
      technician TEXT,
      findings TEXT,
      pest TEXT,
      severity TEXT CHECK(severity IS NULL OR severity IN ('low','medium','high')),
      corrective_action TEXT,
      report_path TEXT,
      cook_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS thermometer_calibrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      thermometer_id TEXT NOT NULL,
      method TEXT NOT NULL
        CHECK(method IN ('ice_point','boiling_point','reference_probe')),
      before_reading_f REAL,
      after_reading_f REAL,
      passed INTEGER NOT NULL DEFAULT 0,
      action_taken TEXT,
      cook_id TEXT,
      calibrated_at TEXT NOT NULL,
      -- Per-probe calibration frequency override in days. NULL means
      -- "use the default 30-day schedule". A positive integer overrides
      -- the default for this probe (e.g. high-use probes every 14 days).
      frequency_days INTEGER,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS tphc_entries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      station_id TEXT,
      item TEXT NOT NULL,
      batch_ref TEXT,
      started_at TEXT NOT NULL,
      cutoff_at TEXT NOT NULL,
      discarded_at TEXT,
      discard_reason TEXT,
      cook_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS sds_registry (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      product_name TEXT NOT NULL,
      manufacturer TEXT,
      hazard_class TEXT,
      storage_location TEXT,
      pdf_path TEXT,
      url TEXT,
      last_reviewed TEXT,
      active INTEGER DEFAULT 1,
      notes TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    , archived_at TEXT);
CREATE TABLE IF NOT EXISTS shift_breaks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      kind TEXT NOT NULL CHECK(kind IN ('meal','rest')),
      started_at TEXT NOT NULL,
      ended_at TEXT,
      duration_min REAL,
      waived INTEGER DEFAULT 0,
      waiver_ref TEXT,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS paid_sick_leave_balances (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      accrual_year INTEGER NOT NULL,
      hours_accrued REAL NOT NULL DEFAULT 0,
      hours_used REAL NOT NULL DEFAULT 0,
      cap_hours REAL NOT NULL DEFAULT 48,
      carryover_hours REAL NOT NULL DEFAULT 0,
      last_accrued_on TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(location_id, cook_id, accrual_year)
    );
CREATE TABLE IF NOT EXISTS tip_pool_distributions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      pool_ref TEXT NOT NULL,
      cook_id TEXT NOT NULL,
      role TEXT,
      kind TEXT NOT NULL
        CHECK(kind IN ('tip_pool','service_charge','direct_tip')),
      amount_cents INTEGER NOT NULL,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS staff_flags (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      flag TEXT NOT NULL,
      effective_from TEXT NOT NULL,
      effective_to TEXT,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS wage_notices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      reason TEXT NOT NULL
        CHECK(reason IN ('hire','rate_change','annual','law_change','other')),
      wage_rate_cents INTEGER NOT NULL,
      pay_basis TEXT NOT NULL
        CHECK(pay_basis IN ('hourly','salary','commission','tipped')),
      tip_credit_cents INTEGER,
      document_path TEXT,
      signed_on TEXT NOT NULL,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS employee_health_acknowledgments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT DEFAULT 'default',
      cook_id TEXT NOT NULL,
      policy_version TEXT NOT NULL,
      document_path TEXT,
      signed_on TEXT NOT NULL,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS audit_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      location_id TEXT DEFAULT 'default',
      actor_cook_id TEXT,
      actor_source TEXT NOT NULL,
      entity TEXT NOT NULL,
      entity_id INTEGER,
      action TEXT NOT NULL
        CHECK(action IN ('insert','update','delete','correction','view')),
      replaces_id INTEGER,
      payload_json TEXT,
      note TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS kds_ticket_states (
      ticket_id TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      bumped_at TEXT NOT NULL,
      bumped_station TEXT,
      bumped_pin_hash TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (ticket_id, location_id)
    );
CREATE TABLE IF NOT EXISTS temp_pins (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      pin_hash TEXT NOT NULL UNIQUE,
      label TEXT NOT NULL,
      scopes_json TEXT NOT NULL,
      issued_by TEXT,
      issued_at TEXT NOT NULL DEFAULT (datetime('now')),
      expires_at TEXT NOT NULL,
      revoked_at TEXT
    );
CREATE TABLE IF NOT EXISTS beo_courses (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id INTEGER NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      course_label TEXT NOT NULL,
      fire_at TEXT NOT NULL,
      notes TEXT,
      sort_order INTEGER DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')), station_id TEXT,
      FOREIGN KEY (event_id) REFERENCES beo_events(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS beo_signatures (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id INTEGER NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      signed_name TEXT NOT NULL,
      signed_at TEXT NOT NULL DEFAULT (datetime('now')),
      ip_addr TEXT,
      user_agent TEXT,
      FOREIGN KEY (event_id) REFERENCES beo_events(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS entities_employees (
      uuid TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      primary_email TEXT,
      primary_phone TEXT,
      active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS entities_vendors (
      uuid TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      category TEXT,
      active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS entities_menu_items (
      uuid TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      category TEXT,
      base_price REAL,
      active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS entities_recipes (
      uuid TEXT PRIMARY KEY,
      slug TEXT NOT NULL,
      display_name TEXT NOT NULL,
      yield_qty REAL,
      yield_unit TEXT,
      category TEXT,
      active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(slug, location_id)
    );
CREATE TABLE IF NOT EXISTS entities_ingredients (
      uuid TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      ingredient_key TEXT NOT NULL,
      category TEXT,
      default_unit TEXT,
      active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(ingredient_key)
    );
CREATE TABLE IF NOT EXISTS entities_events (
      uuid TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      event_date TEXT,
      event_time TEXT,
      venue TEXT,
      headliner TEXT,
      guest_count INTEGER,
      status TEXT NOT NULL DEFAULT 'planned'
        CHECK(status IN ('planned','confirmed','cancelled','completed')),
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS entities_purchase_orders (
      uuid TEXT PRIMARY KEY,
      vendor_uuid TEXT NOT NULL REFERENCES entities_vendors(uuid),
      po_number TEXT,
      ordered_at TEXT,
      expected_at TEXT,
      received_at TEXT,
      status TEXT NOT NULL DEFAULT 'open'
        CHECK(status IN ('open','sent','received','cancelled','closed')),
      total_amount REAL,
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS external_ids (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      entity_type TEXT NOT NULL CHECK(entity_type IN
        ('employee','vendor','menu_item','recipe','ingredient',
         'purchase_order','event')),
      entity_uuid TEXT NOT NULL,
      source_system TEXT NOT NULL,
      external_id TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      metadata_json TEXT,
      first_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
      last_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(source_system, external_id, location_id, entity_type)
    );
CREATE TABLE IF NOT EXISTS sevenshifts_users (
      seven_id TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      employee_uuid TEXT,
      first_name TEXT,
      last_name TEXT,
      preferred_name TEXT,
      email TEXT,
      phone TEXT,
      employee_id TEXT,
      role_ids_json TEXT,
      hire_date TEXT,
      active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
      raw_json TEXT,
      ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (seven_id, location_id)
    );
CREATE TABLE IF NOT EXISTS sevenshifts_shifts (
      seven_id TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      user_seven_id TEXT,
      employee_uuid TEXT,
      role_id TEXT,
      department_id TEXT,
      start_at TEXT,
      end_at TEXT,
      published INTEGER,
      deleted INTEGER NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
      raw_json TEXT,
      ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (seven_id, location_id)
    );
CREATE TABLE IF NOT EXISTS sevenshifts_time_punches (
      seven_id TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      user_seven_id TEXT,
      employee_uuid TEXT,
      role_id TEXT,
      clocked_in_at TEXT,
      clocked_out_at TEXT,
      hours_worked REAL,
      approved INTEGER,
      raw_json TEXT,
      ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (seven_id, location_id)
    );
CREATE TABLE IF NOT EXISTS prism_events (
      prism_id TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      event_uuid TEXT,
      display_name TEXT,
      event_date TEXT,
      doors_at TEXT,
      show_at TEXT,
      venue TEXT,
      headliner TEXT,
      supports_json TEXT,
      ticket_count INTEGER,
      capacity INTEGER,
      status TEXT,
      raw_json TEXT,
      ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (prism_id, location_id)
    );
CREATE TABLE IF NOT EXISTS sales_depletion_runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL,
      period_label TEXT NOT NULL,
      shift_date TEXT NOT NULL,
      sales_rows_processed INTEGER NOT NULL DEFAULT 0,
      depletions_written INTEGER NOT NULL DEFAULT 0,
      unresolved_dish_count INTEGER NOT NULL DEFAULT 0,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS sync_feed (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      -- UUIDv7. Globally unique; idempotency key for replay.
      op_id TEXT NOT NULL UNIQUE,
      -- Source table on the originating host (e.g. 'cooling_log').
      table_name TEXT NOT NULL,
      -- Multi-tenant scope; matches the source row's location_id.
      location_id TEXT NOT NULL DEFAULT 'default',
      -- Operation kind; see SyncOpKind in lib/syncFeed.ts.
      op_kind TEXT NOT NULL
        CHECK(op_kind IN ('insert','update','delete','delete-batch')),
      -- Stringified PK (or batch key for delete-batch).
      row_pk TEXT NOT NULL,
      -- JSON-encoded row body. '{}' for delete; rows-array payload for
      -- delete-batch envelopes.
      row_json TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      -- Originating instance identity. Pair: (host, started_at) per
      -- lib/hubFailover.ts.
      source_host TEXT NOT NULL,
      source_started_at TEXT NOT NULL
    );
CREATE TABLE IF NOT EXISTS replay_checkpoints (
      peer_id TEXT NOT NULL,
      feed_scope TEXT NOT NULL DEFAULT 'local',
      last_op_rowid INTEGER NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (peer_id, feed_scope)
    );
CREATE TABLE IF NOT EXISTS peer_trust (
      pubkey_hex TEXT PRIMARY KEY,
      fingerprint TEXT NOT NULL UNIQUE,
      label TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      last_seen_at TEXT,
      revoked INTEGER NOT NULL DEFAULT 0
    );
CREATE TABLE IF NOT EXISTS manager_pin_users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL DEFAULT 'default',
      name TEXT NOT NULL,
      pin_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'manager'
        CHECK(role IN ('manager','owner')),
      is_active INTEGER NOT NULL DEFAULT 1
        CHECK(is_active IN (0,1)),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      disabled_at TEXT
    );
CREATE TABLE IF NOT EXISTS performance_reviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      cook_name TEXT NOT NULL,
      cook_uuid TEXT,
      review_date TEXT NOT NULL,
      punctuality_score INTEGER,
      technique_score INTEGER,
      speed_score INTEGER,
      notes TEXT,
      reviewer_name TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS lari_conversation_turns (
      schemaVersion TEXT NOT NULL DEFAULT 'lari_conversation_turn_v1'
        CHECK(schemaVersion = 'lari_conversation_turn_v1'),
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      location_id TEXT NOT NULL,
      cook_id TEXT NOT NULL,
      conversation_session_id TEXT NOT NULL,
      user_content TEXT NOT NULL,
      assistant_content TEXT NOT NULL,
      manager_tier INTEGER NOT NULL DEFAULT 0 CHECK(manager_tier IN (0, 1)),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      expires_at TEXT NOT NULL
    );
CREATE TABLE IF NOT EXISTS allergen_attestations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      recipe_slug TEXT NOT NULL,
      location_id TEXT NOT NULL DEFAULT 'default',
      allergens_json TEXT NOT NULL DEFAULT '[]',
      recipe_fingerprint TEXT NOT NULL,
      attested_by TEXT NOT NULL,
      note TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS idempotency_keys (
        key             TEXT PRIMARY KEY,
        method          TEXT NOT NULL,
        path            TEXT NOT NULL,
        request_hash    TEXT NOT NULL,
        response_status INTEGER NOT NULL,
        response_body   TEXT NOT NULL,
        created_at      TEXT NOT NULL DEFAULT (datetime('now'))
      , status TEXT NOT NULL DEFAULT 'complete');
CREATE TABLE IF NOT EXISTS shows (
      id              INTEGER PRIMARY KEY,
      location_id     TEXT NOT NULL DEFAULT 'default',
      band_name       TEXT NOT NULL,
      show_date       TEXT NOT NULL,
      price           REAL,
      door_tix        TEXT,
      status_json     TEXT NOT NULL DEFAULT '{}',
      source_row      INTEGER NOT NULL,
      ingested_at     TEXT NOT NULL,
      ingest_run_id   INTEGER NOT NULL REFERENCES ingest_runs(id)
    );
CREATE TABLE IF NOT EXISTS shows_archive (
      id            INTEGER PRIMARY KEY,
      location_id   TEXT NOT NULL DEFAULT 'default',
      band_name     TEXT NOT NULL,
      show_date     TEXT NOT NULL,
      era_year      INTEGER,
      source_row    INTEGER NOT NULL,
      ingested_at   TEXT NOT NULL,
      ingest_run_id INTEGER NOT NULL REFERENCES ingest_runs(id)
    );
CREATE TABLE IF NOT EXISTS tiktok_ideas (
      id            INTEGER PRIMARY KEY,
      location_id   TEXT NOT NULL DEFAULT 'default',
      idea          TEXT NOT NULL,
      video_content TEXT,
      staff_needed  TEXT,
      props         TEXT,
      notes         TEXT,
      source_row    INTEGER NOT NULL,
      ingested_at   TEXT NOT NULL,
      ingest_run_id INTEGER NOT NULL REFERENCES ingest_runs(id)
    );
CREATE TABLE IF NOT EXISTS stage_setups (
      id                     INTEGER PRIMARY KEY AUTOINCREMENT,
      show_id                INTEGER NOT NULL REFERENCES shows(id),
      location_id            TEXT NOT NULL DEFAULT 'default',
      room_config            TEXT NOT NULL,
      run_of_show_json       TEXT NOT NULL DEFAULT '[]',
      hospitality_rider_json TEXT NOT NULL DEFAULT '{}',
      tech_rider_json        TEXT NOT NULL DEFAULT '{}',
      notes                  TEXT,
      created_at             TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at             TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE (show_id, location_id)
    );
CREATE TABLE IF NOT EXISTS sound_scenes (
      id               INTEGER PRIMARY KEY AUTOINCREMENT,
      show_id          INTEGER NOT NULL REFERENCES shows(id),
      location_id      TEXT NOT NULL DEFAULT 'default',
      scene_name       TEXT NOT NULL,
      plot_json        TEXT NOT NULL,
      spl_limit_db     REAL,
      notes            TEXT,
      saved_by_cook_id TEXT,
      saved_at         TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS spl_readings (
      id               INTEGER PRIMARY KEY AUTOINCREMENT,
      show_id          INTEGER NOT NULL REFERENCES shows(id),
      location_id      TEXT NOT NULL DEFAULT 'default',
      scene_id         INTEGER REFERENCES sound_scenes(id),
      db_value         REAL NOT NULL,
      taken_at         TEXT NOT NULL DEFAULT (datetime('now')),
      taken_by_cook_id TEXT,
      notes            TEXT
    );
CREATE TABLE IF NOT EXISTS box_office_lines (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      show_id       INTEGER NOT NULL REFERENCES shows(id),
      location_id   TEXT NOT NULL DEFAULT 'default',
      source        TEXT NOT NULL CHECK (source IN ('dice','walkup','comp','will_call','guestlist')),
      ticket_class  TEXT,
      qty           INTEGER NOT NULL DEFAULT 1,
      face_price    REAL,
      fees          REAL,
      external_ref  TEXT,
      scanned_at    TEXT,
      notes         TEXT,
      created_at    TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS show_deals (
      id                 INTEGER PRIMARY KEY AUTOINCREMENT,
      show_id            INTEGER NOT NULL REFERENCES shows(id),
      location_id        TEXT NOT NULL DEFAULT 'default',
      guarantee_cents    INTEGER NOT NULL DEFAULT 0,
      vs_pct_after_costs REAL,
      costs_off_top_json TEXT NOT NULL DEFAULT '[]',
      buyout_cents       INTEGER NOT NULL DEFAULT 0,
      notes              TEXT,
      updated_at         TEXT NOT NULL DEFAULT (datetime('now')),
      updated_by_cook_id TEXT,
      UNIQUE (show_id, location_id)
    );
CREATE TABLE IF NOT EXISTS specials (
      id                 TEXT PRIMARY KEY,
      location_id        TEXT NOT NULL DEFAULT 'default',
      name               TEXT NOT NULL,
      pantry_text        TEXT NOT NULL DEFAULT '',
      prompt_text        TEXT NOT NULL DEFAULT '',
      ai_answer          TEXT NOT NULL DEFAULT '',
      ai_model           TEXT NOT NULL DEFAULT '',
      cost_breakdown     TEXT,
      cost_total         REAL,
      scratch_notes      TEXT NOT NULL DEFAULT '',
      sources            TEXT,
      last_exported_at   INTEGER,
      created_at         INTEGER NOT NULL,
      updated_at         INTEGER NOT NULL,
      archived_at        INTEGER
    );
CREATE TABLE IF NOT EXISTS specials_promotions (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      special_id      TEXT NOT NULL,
      location_id     TEXT NOT NULL DEFAULT 'default',
      menu_item_name  TEXT NOT NULL,
      servings        REAL NOT NULL DEFAULT 1,
      components_json TEXT NOT NULL DEFAULT '[]',
      promoted_at     INTEGER NOT NULL,
      updated_at      INTEGER NOT NULL
    );
CREATE TABLE IF NOT EXISTS kds_tickets (
      id            TEXT PRIMARY KEY,
      location_id   TEXT NOT NULL DEFAULT 'default',
      order_number  TEXT NOT NULL,
      placed_at     TEXT NOT NULL,
      destination   TEXT,
      bumped_at     TEXT,
      created_by_cook_id TEXT,
      created_at    TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE TABLE IF NOT EXISTS kds_ticket_lines (
      id          TEXT PRIMARY KEY,
      ticket_id   TEXT NOT NULL REFERENCES kds_tickets(id) ON DELETE CASCADE,
      sort_order  INTEGER NOT NULL DEFAULT 0,
      item_name   TEXT NOT NULL,
      quantity    INTEGER NOT NULL CHECK (quantity >= 1),
      station     TEXT NOT NULL,
      modifiers   TEXT
    );
CREATE TABLE IF NOT EXISTS schema_migrations (
      version    INTEGER PRIMARY KEY,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
CREATE INDEX IF NOT EXISTS idx_lce_shift ON line_check_entries(shift_date, station_id);
CREATE INDEX IF NOT EXISTS idx_signoff_shift ON station_signoffs(shift_date, station_id);
CREATE INDEX IF NOT EXISTS idx_86_shift ON eighty_six(shift_date, resolved_at);
CREATE INDEX IF NOT EXISTS idx_inv_shift ON inventory_updates(shift_date, station_id);
CREATE INDEX IF NOT EXISTS idx_inv_counts_loc_date
      ON inventory_counts(location_id, count_date DESC);
CREATE INDEX IF NOT EXISTS idx_inv_count_lines_count
      ON inventory_count_lines(count_id);
CREATE INDEX IF NOT EXISTS idx_inv_par_loc_cat
      ON inventory_par(location_id, category, ingredient);
CREATE INDEX IF NOT EXISTS idx_prep_tasks_loc_date
      ON prep_tasks(location_id, shift_date, status);
CREATE INDEX IF NOT EXISTS idx_prep_tasks_station
      ON prep_tasks(location_id, shift_date, station_id);
CREATE INDEX IF NOT EXISTS idx_prep_par_loc_station
      ON prep_par(location_id, station_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_reservations_loc_at
      ON reservations(location_id, reservation_at);
CREATE INDEX IF NOT EXISTS idx_reservations_status
      ON reservations(location_id, status, reservation_at);
CREATE INDEX IF NOT EXISTS idx_waitlist_parties_loc_status
      ON waitlist_parties(location_id, status, joined_at);
CREATE INDEX IF NOT EXISTS idx_dining_tables_loc_status
      ON dining_tables(location_id, status);
CREATE INDEX IF NOT EXISTS idx_service_hours_loc
      ON service_hours(location_id, day_of_week);
CREATE INDEX IF NOT EXISTS idx_preshift_date
      ON preshift_notes(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_vp_loc ON vendor_prices(location_id);
CREATE INDEX IF NOT EXISTS idx_vph_loc_vendor_sku
      ON vendor_prices_history(location_id, vendor, sku);
CREATE INDEX IF NOT EXISTS idx_vph_snapshot_at
      ON vendor_prices_history(snapshot_at);
CREATE INDEX IF NOT EXISTS idx_vph_loc_snapshot_shock
      ON vendor_prices_history(location_id, snapshot_at DESC)
      WHERE vendor IS NOT NULL AND sku IS NOT NULL AND unit_price IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vph_ingredient
      ON vendor_prices_history(ingredient);
CREATE INDEX IF NOT EXISTS idx_recipe_photos_slug
      ON recipe_photos(location_id, recipe_slug, id DESC)
      WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_margin_snapshots_loc_id
      ON margin_snapshots(location_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_dish_coverage_snapshots_loc_id
      ON dish_coverage_snapshots(location_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_accounting_variance_loc_id
      ON accounting_variance(location_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_bom_recipe ON bom_lines(recipe_id, location_id);
CREATE INDEX IF NOT EXISTS idx_ingest_runs_kind_started ON ingest_runs(kind, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_loc ON sales_lines(location_id);
CREATE INDEX IF NOT EXISTS idx_dish_components_dish
      ON dish_components(location_id, dish_name);
CREATE INDEX IF NOT EXISTS idx_spend_month ON spend_monthly(month, location_id);
CREATE INDEX IF NOT EXISTS idx_beo_line_ev ON beo_line_items(event_id);
CREATE INDEX IF NOT EXISTS idx_beo_prep_ev ON beo_prep_tasks(event_id);
CREATE INDEX IF NOT EXISTS idx_beo_prep_hist_loc_date
      ON beo_prep_history(location_id, event_date);
CREATE INDEX IF NOT EXISTS idx_beo_prep_hist_loc_item
      ON beo_prep_history(location_id, item);
CREATE INDEX IF NOT EXISTS idx_beo_prep_hist_loc_source
      ON beo_prep_history(location_id, source);
CREATE INDEX IF NOT EXISTS idx_equip_loc ON equipment(location_id);
CREATE INDEX IF NOT EXISTS idx_equip_maint_eq ON equipment_maintenance(equipment_id);
CREATE INDEX IF NOT EXISTS idx_equip_parts_eq ON equipment_parts(equipment_id);
CREATE INDEX IF NOT EXISTS idx_equip_sched_eq ON equipment_maintenance_schedule(equipment_id);
CREATE INDEX IF NOT EXISTS idx_temp_log_shift ON temp_log(shift_date, location_id, point_id);
CREATE INDEX IF NOT EXISTS idx_toast_daily_loc_date ON toast_sales_daily(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_toast_sub_inv_date ON toast_subscription_invoices(location_id, invoice_date);
CREATE INDEX IF NOT EXISTS idx_toast_sub_lines_inv ON toast_subscription_invoice_lines(location_id, invoice_no);
CREATE INDEX IF NOT EXISTS idx_toast_sub_lines_item ON toast_subscription_invoice_lines(location_id, item, invoice_date);
CREATE INDEX IF NOT EXISTS idx_cbo_drain
      ON cloud_bridge_outbox(dead_letter, claimed_at, id);
CREATE INDEX IF NOT EXISTS idx_cooling_status
      ON cooling_log(location_id, status, shift_date);
CREATE INDEX IF NOT EXISTS idx_cooling_open
      ON cooling_log(location_id, started_at)
      WHERE status = 'in_progress';
CREATE INDEX IF NOT EXISTS idx_datemarks_active
      ON date_marks(location_id, discard_on)
      WHERE discarded_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_receiving_shift
      ON receiving_log(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_receiving_shellstock
      ON receiving_log(shellstock_tag_ref)
      WHERE shellstock_tag_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sanitizer_shift
      ON sanitizer_checks(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_sickworker_active
      ON sick_worker_reports(location_id, cook_id)
      WHERE return_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_staffcerts_expiry
      ON staff_certifications(location_id, expires_on)
      WHERE active = 1;
CREATE INDEX IF NOT EXISTS idx_staffcerts_cook
      ON staff_certifications(location_id, cook_id, cert_type);
CREATE INDEX IF NOT EXISTS idx_shiftpic_date
      ON shift_pic(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_cleansched_due
      ON cleaning_schedule(location_id, next_due)
      WHERE active = 1;
CREATE INDEX IF NOT EXISTS idx_cleanlog_shift
      ON cleaning_log(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_cleanlog_sched
      ON cleaning_log(schedule_id);
CREATE INDEX IF NOT EXISTS idx_pest_shift
      ON pest_control_log(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_thermcal_recent
      ON thermometer_calibrations(location_id, thermometer_id, calibrated_at DESC);
CREATE INDEX IF NOT EXISTS idx_tphc_open
      ON tphc_entries(location_id, cutoff_at)
      WHERE discarded_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sds_active
      ON sds_registry(location_id, active);
CREATE INDEX IF NOT EXISTS idx_breaks_shift
      ON shift_breaks(location_id, shift_date, cook_id);
CREATE INDEX IF NOT EXISTS idx_tip_shift
      ON tip_pool_distributions(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_tip_pool
      ON tip_pool_distributions(pool_ref);
CREATE INDEX IF NOT EXISTS idx_staffflags_active
      ON staff_flags(location_id, cook_id, flag)
      WHERE effective_to IS NULL;
CREATE INDEX IF NOT EXISTS idx_wagenotice_cook
      ON wage_notices(location_id, cook_id, signed_on DESC);
CREATE INDEX IF NOT EXISTS idx_healthack_cook
      ON employee_health_acknowledgments(location_id, cook_id, signed_on DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity
      ON audit_events(entity, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_shift
      ON audit_events(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_audit_recent_loc_created
      ON audit_events(location_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kds_states_recent
      ON kds_ticket_states(location_id, bumped_at DESC);
CREATE INDEX IF NOT EXISTS idx_temp_pins_active
      ON temp_pins(location_id, expires_at)
      WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_beo_courses_loc_fire
      ON beo_courses(location_id, fire_at);
CREATE INDEX IF NOT EXISTS idx_beo_courses_event
      ON beo_courses(event_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_beo_signatures_event
      ON beo_signatures(event_id, signed_at);
CREATE INDEX IF NOT EXISTS idx_entities_menu_items_loc
      ON entities_menu_items(location_id, active);
CREATE INDEX IF NOT EXISTS idx_entities_events_date
      ON entities_events(location_id, event_date);
CREATE INDEX IF NOT EXISTS idx_entities_po_vendor
      ON entities_purchase_orders(vendor_uuid, status);
CREATE INDEX IF NOT EXISTS idx_entities_po_loc_date
      ON entities_purchase_orders(location_id, ordered_at);
CREATE INDEX IF NOT EXISTS idx_external_ids_uuid
      ON external_ids(entity_uuid, entity_type);
CREATE INDEX IF NOT EXISTS idx_external_ids_lookup
      ON external_ids(source_system, entity_type, location_id);
CREATE INDEX IF NOT EXISTS idx_sevenshifts_shifts_user
      ON sevenshifts_shifts(user_seven_id, location_id, start_at);
CREATE INDEX IF NOT EXISTS idx_sevenshifts_punches_user
      ON sevenshifts_time_punches(user_seven_id, location_id, clocked_in_at);
CREATE INDEX IF NOT EXISTS idx_prism_events_date
      ON prism_events(location_id, event_date);
CREATE INDEX IF NOT EXISTS idx_sales_depletion_runs_period
      ON sales_depletion_runs(location_id, period_label, id DESC);
CREATE INDEX IF NOT EXISTS idx_sync_feed_replay
      ON sync_feed(id);
CREATE INDEX IF NOT EXISTS idx_sync_feed_source
      ON sync_feed(source_host, source_started_at, id);
CREATE INDEX IF NOT EXISTS idx_sync_feed_table
      ON sync_feed(location_id, table_name, id);
CREATE INDEX IF NOT EXISTS idx_peer_trust_fingerprint
      ON peer_trust(fingerprint);
CREATE UNIQUE INDEX IF NOT EXISTS idx_manager_pin_users_active_pin
      ON manager_pin_users(location_id, pin_hash)
      WHERE is_active = 1;
CREATE INDEX IF NOT EXISTS idx_manager_pin_users_active
      ON manager_pin_users(location_id, is_active, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_allergen_attestations_latest
      ON allergen_attestations(location_id, recipe_slug, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_updates_receiving_log_id
         ON inventory_updates(receiving_log_id)
         WHERE receiving_log_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_receiving_log_sync_source
         ON receiving_log(sync_source_host, sync_source_started_at, sync_source_pk)
         WHERE sync_source_host IS NOT NULL
           AND sync_source_started_at IS NOT NULL
           AND sync_source_pk IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_updates_sync_source
         ON inventory_updates(sync_source_host, sync_source_started_at, sync_source_pk)
         WHERE sync_source_host IS NOT NULL
           AND sync_source_started_at IS NOT NULL
           AND sync_source_pk IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_idempotency_created
        ON idempotency_keys(created_at);
CREATE INDEX IF NOT EXISTS idx_sales_service_date
         ON sales_lines(service_date, location_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dish_components_recipe_unique
          ON dish_components(location_id, dish_name, recipe_slug)
          WHERE component_type = 'recipe';
CREATE UNIQUE INDEX IF NOT EXISTS idx_dish_components_vendor_unique
          ON dish_components(location_id, dish_name, vendor_ingredient)
          WHERE component_type = 'vendor_item';
CREATE UNIQUE INDEX IF NOT EXISTS idx_beo_events_share_token
        ON beo_events(share_token) WHERE share_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_lce_loc_date ON line_check_entries(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_signoff_loc ON station_signoffs(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_86_loc_date ON eighty_six(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_inv_loc_date ON inventory_updates(location_id, shift_date);
CREATE INDEX IF NOT EXISTS idx_gold_stars_live ON gold_stars(location_id, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_psc_vendor_sku ON pack_size_changes(vendor, sku);
CREATE INDEX IF NOT EXISTS idx_psc_ack ON pack_size_changes(acknowledged, detected_at);
CREATE INDEX IF NOT EXISTS idx_vp_master ON vendor_prices(master_id);
CREATE INDEX IF NOT EXISTS idx_bom_master ON bom_lines(master_id);
CREATE INDEX IF NOT EXISTS idx_perf_review_cook ON performance_reviews(cook_name, cook_uuid, location_id);
CREATE INDEX IF NOT EXISTS idx_lari_conversation_partition
      ON lari_conversation_turns(location_id, cook_id, conversation_session_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_lari_conversation_expiry
      ON lari_conversation_turns(expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_service_hours_null_safe
        ON service_hours(location_id, day_of_week)
        WHERE service_label IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_preshift_null_safe
        ON preshift_notes(location_id, shift_date)
        WHERE service_label IS NULL;
CREATE INDEX IF NOT EXISTS idx_shows_date ON shows(location_id, show_date);
CREATE INDEX IF NOT EXISTS idx_shows_band ON shows(location_id, band_name);
CREATE INDEX IF NOT EXISTS idx_shows_archive_date ON shows_archive(location_id, show_date);
CREATE INDEX IF NOT EXISTS idx_shows_archive_band ON shows_archive(location_id, band_name);
CREATE INDEX IF NOT EXISTS idx_stage_setups_show
      ON stage_setups(show_id, location_id);
CREATE INDEX IF NOT EXISTS idx_sound_scenes_show
      ON sound_scenes(show_id, location_id);
CREATE INDEX IF NOT EXISTS idx_spl_readings_show
      ON spl_readings(show_id, location_id, taken_at);
CREATE INDEX IF NOT EXISTS idx_box_office_show
      ON box_office_lines(show_id, location_id);
CREATE INDEX IF NOT EXISTS idx_box_office_source_ext
      ON box_office_lines(source, external_ref);
CREATE UNIQUE INDEX IF NOT EXISTS idx_box_office_external_ref_unique
      ON box_office_lines(source, external_ref)
      WHERE external_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_show_deals_show
      ON show_deals(show_id, location_id);
CREATE INDEX IF NOT EXISTS idx_specials_loc_created
      ON specials(location_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_specials_active
      ON specials(location_id, archived_at) WHERE archived_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_specials_promotions_special
      ON specials_promotions(location_id, special_id);
CREATE INDEX IF NOT EXISTS idx_specials_promotions_menu_item
      ON specials_promotions(location_id, menu_item_name);
CREATE INDEX IF NOT EXISTS idx_kds_tickets_active
      ON kds_tickets(location_id, placed_at DESC)
      WHERE bumped_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_kds_ticket_lines_ticket
      ON kds_ticket_lines(ticket_id, sort_order, id);
INSERT OR IGNORE INTO "locations" ("id", "name", "created_at", "capacity", "tax_rate", "service_fee_pct", "phone", "address") VALUES ('default', 'The Lariat', '2026-07-08 12:04:50', NULL, 0.0675, 20, NULL, NULL);
INSERT OR IGNORE INTO "schema_migrations" ("version", "applied_at") VALUES (4, '2026-07-08 12:04:50');
