import XCTest
@testable import LariatModel

/// SAFETY-CRITICAL fingerprint parity. The expected SHA-256 values below were
/// generated by running the web `lib/allergenAttestations.ts
/// computeRecipeFingerprint` under node against these exact fixtures (the
/// same QUESO/SALSA fixtures as `tests/js/test-allergen-attestations.mjs`).
/// An attestation recorded on the web must read back `attested` (not `stale`)
/// on native, and vice versa — so these hashes must never drift.
final class AllergenAttestationComputeTests: XCTestCase {
    private let salsa = AllergenRecipe(
        slug: "salsa", name: "Blackened Tomato Salsa",
        ingredients: [.init(item: "Tomato"), .init(item: "Worcestershire")],
        allergens: ["fish", "wheat"])

    private let queso = AllergenRecipe(
        slug: "queso", name: "Queso",
        ingredients: [.init(item: "Milk"), .init(item: "Cheddar")],
        allergens: ["fish", "milk", "wheat"],
        subRecipes: ["salsa"])

    // ── Fingerprint oracle hashes (node-generated) ──────────────────────
    //
    // Regenerated 2026-07-14 after the web fingerprint folded each node's
    // DERIVED allergen output into the canonical shape (PR #539 Critical #2:
    // {slug, ingredients, sub_recipes, allergens} — allergens LAST), so a
    // heuristic/data-version change that alters the answer stales the
    // attestation even when ingredient names are unchanged.

    func testFingerprintMatchesWebForQuesoTree() {
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [queso, salsa]),
            "b14b38c0db0c18bee7ac7e700a46ae9649910cef362cb416ba770b49c129db40")
    }

    func testFingerprintMatchesWebForSalsa() {
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "salsa", recipes: [queso, salsa]),
            "131c17a48b2794b1fbfb01f74e31e6d0e2905aa83d794130cef3f13f14f8c058")
    }

    func testFingerprintChangesWhenOwnIngredientsChange() {
        let quesoWithFlour = AllergenRecipe(
            slug: "queso", name: "Queso",
            ingredients: queso.ingredients + [.init(item: "Flour")],
            allergens: queso.allergens, subRecipes: queso.subRecipes)
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [quesoWithFlour, salsa]),
            "38273938072b09d1484d32e41c46ed8ac6ddea9ea547a38b46a0c82e6fd65e55")
    }

    func testFingerprintChangesWhenSubRecipeChanges() {
        let salsaWithPeanut = AllergenRecipe(
            slug: "salsa", name: "Blackened Tomato Salsa",
            ingredients: salsa.ingredients + [.init(item: "Peanut oil")],
            allergens: salsa.allergens)
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [queso, salsaWithPeanut]),
            "f5cf77a8b935dfdff938e0fbbc0cdfdf3a15ff69c890e9123738b431a8861c4c")
    }

    func testFingerprintChangesWhenOnlyDerivedAllergensChange() {
        // The heuristic/data version can change a recipe's allergen OUTPUT
        // without touching ingredient item names (keyword-map update,
        // allergen_matrix override). The fingerprint must move so the
        // manager's signoff stales — mirrors the web test of the same name.
        let quesoSesame = AllergenRecipe(
            slug: "queso", name: "Queso",
            ingredients: queso.ingredients,
            allergens: ["fish", "milk", "wheat", "sesame"],
            subRecipes: queso.subRecipes)
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [quesoSesame, salsa]),
            "735c7800f0909853bffd709f85e9bcb18047d611c73a6df5a2573b05f7d9a7b6")
        XCTAssertNotEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [quesoSesame, salsa]),
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [queso, salsa]))
    }

    func testFingerprintNilForUnknownRecipe() {
        XCTAssertNil(AllergenAttestationCompute.computeRecipeFingerprint(slug: "nope", recipes: [queso, salsa]))
    }

    func testFingerprintWithDanglingSubRecipeAndBlankItems() {
        // Dangling sub-recipe link contributes its slug with empty
        // ingredients/sub_recipes; blank items drop; items trim + lowercase.
        let dangle = AllergenRecipe(
            slug: "dangle", name: "D",
            ingredients: [.init(item: " Basil "), .init(item: "")],
            subRecipes: ["ghost"])
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "dangle", recipes: [dangle]),
            "0c07c44d16758bcb270069323f3cfcef883756b153348a0e5eb73376186ecfda")
    }

    func testFingerprintIsCycleSafe() {
        let a = AllergenRecipe(slug: "a", name: "A", ingredients: [.init(item: "X")], subRecipes: ["b"])
        let b = AllergenRecipe(slug: "b", name: "B", ingredients: [.init(item: "Y")], subRecipes: ["a"])
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "a", recipes: [a, b]),
            "20a667bbdedfef4709a5824471d3a4b0f7db6d4b79ac7baf03c8f2c3b1026136")
    }

    func testFingerprintJsonEscapingAndUnicodeMatchWeb() {
        // Quotes escape as \" and \n as \\n inside JSON.stringify; non-ASCII
        // hashes as UTF-8 — pinned against the node hash of this fixture.
        let u = AllergenRecipe(
            slug: "uni", name: "U",
            ingredients: [.init(item: "Jalapeño \"hot\""), .init(item: "Crème\nfraîche")])
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "uni", recipes: [u]),
            "f5868e32f1208e9d4fee8a95cb795d83a902d3279c03f8fb555b059da79c55aa")
    }

    // ── normalizeAllergens ──────────────────────────────────────────────

    func testNormalizeAllergensTrimsLowercasesDedupesSorts() {
        XCTAssertEqual(
            AllergenAttestationCompute.normalizeAllergens(["Milk", "fish", "wheat", "milk "]),
            ["fish", "milk", "wheat"])
    }

    func testNormalizeAllergensClipsTo64AndDropsEmpties() {
        let long = String(repeating: "x", count: 80)
        let result = AllergenAttestationCompute.normalizeAllergens([long, "", "   "])
        XCTAssertEqual(result.count, 1)
        XCTAssertEqual(result[0].count, 64)
    }

    // ── parseAllergensJson ──────────────────────────────────────────────

    func testParseAllergensJson() {
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson(#"["fish","milk"]"#), ["fish", "milk"])
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson("junk"), [])
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson(#"{"not":"array"}"#), [])
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson(#"["a",1,null,"b"]"#), ["a", "b"])
    }

    // ── status ──────────────────────────────────────────────────────────

    private func record(fingerprint: String) -> AllergenAttestationRecord {
        AllergenAttestationRecord(
            id: 1, recipeSlug: "queso", locationId: "default",
            allergensJson: "[]", recipeFingerprint: fingerprint,
            attestedBy: "Dana", note: nil, createdAt: "2026-07-02 10:00:00")
    }

    func testStatusUnattestedWithoutRow() {
        XCTAssertEqual(AllergenAttestationCompute.status(latest: nil, currentFingerprint: "abc"), .unattested)
    }

    func testStatusAttestedWhenFingerprintMatches() {
        XCTAssertEqual(
            AllergenAttestationCompute.status(latest: record(fingerprint: "abc"), currentFingerprint: "abc"),
            .attested)
    }

    func testStatusStaleWhenFingerprintDiffersOrRecipeGone() {
        XCTAssertEqual(
            AllergenAttestationCompute.status(latest: record(fingerprint: "abc"), currentFingerprint: "def"),
            .stale)
        // Recipe removed from the cache → current fingerprint nil → stale,
        // NEVER attested (fail-safe direction).
        XCTAssertEqual(
            AllergenAttestationCompute.status(latest: record(fingerprint: "abc"), currentFingerprint: nil),
            .stale)
    }
}
