import XCTest
@testable import LariatModel

/// SAFETY-CRITICAL fingerprint parity. The expected SHA-256 values below were
/// generated by running the web `lib/allergenAttestations.ts
/// computeRecipeFingerprint` under node against these exact fixtures (the
/// same QUESO/SALSA fixtures as `tests/js/test-allergen-attestations.mjs`).
/// An attestation recorded on the web must read back `attested` (not `stale`)
/// on native, and vice versa — so these hashes must never drift.
final class AllergenAttestationComputeTests: XCTestCase {
    private let salsa = AllergenRecipe(
        slug: "salsa", name: "Blackened Tomato Salsa",
        ingredients: [.init(item: "Tomato"), .init(item: "Worcestershire")],
        allergens: ["fish", "wheat"])

    private let queso = AllergenRecipe(
        slug: "queso", name: "Queso",
        ingredients: [.init(item: "Milk"), .init(item: "Cheddar")],
        allergens: ["fish", "milk", "wheat"],
        subRecipes: ["salsa"])

    // ── Fingerprint oracle hashes (node-generated) ──────────────────────

    func testFingerprintMatchesWebForQuesoTree() {
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [queso, salsa]),
            "2c7effd28593aff32b16a2612a8891d90f3e50c8856445cd104ee2c49c10a86c")
    }

    func testFingerprintMatchesWebForSalsa() {
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "salsa", recipes: [queso, salsa]),
            "4741b94d19fb474bf5f92de1eb6f14050906fcefdba937e756671d9a66b191d5")
    }

    func testFingerprintChangesWhenOwnIngredientsChange() {
        let quesoWithFlour = AllergenRecipe(
            slug: "queso", name: "Queso",
            ingredients: queso.ingredients + [.init(item: "Flour")],
            allergens: queso.allergens, subRecipes: queso.subRecipes)
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [quesoWithFlour, salsa]),
            "cd7b2fba9fef8bbdfa961cbc98f58b5b9f3a609924def65ac0444bfe171d1300")
    }

    func testFingerprintChangesWhenSubRecipeChanges() {
        let salsaWithPeanut = AllergenRecipe(
            slug: "salsa", name: "Blackened Tomato Salsa",
            ingredients: salsa.ingredients + [.init(item: "Peanut oil")],
            allergens: salsa.allergens)
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "queso", recipes: [queso, salsaWithPeanut]),
            "185ca130af6b000ce59ff97f87635641cd570e2ef370a013d57178f5f6766bd7")
    }

    func testFingerprintNilForUnknownRecipe() {
        XCTAssertNil(AllergenAttestationCompute.computeRecipeFingerprint(slug: "nope", recipes: [queso, salsa]))
    }

    func testFingerprintWithDanglingSubRecipeAndBlankItems() {
        // Dangling sub-recipe link contributes its slug with empty
        // ingredients/sub_recipes; blank items drop; items trim + lowercase.
        let dangle = AllergenRecipe(
            slug: "dangle", name: "D",
            ingredients: [.init(item: " Basil "), .init(item: "")],
            subRecipes: ["ghost"])
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "dangle", recipes: [dangle]),
            "87ec99709c971907114b04be983431dd9d99d361372fd06dc4e0955d5bcb39d3")
    }

    func testFingerprintIsCycleSafe() {
        let a = AllergenRecipe(slug: "a", name: "A", ingredients: [.init(item: "X")], subRecipes: ["b"])
        let b = AllergenRecipe(slug: "b", name: "B", ingredients: [.init(item: "Y")], subRecipes: ["a"])
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "a", recipes: [a, b]),
            "02927624001c52503c86a6cd23484f519ce17842a411f9a21abc8536849b7db9")
    }

    func testFingerprintJsonEscapingAndUnicodeMatchWeb() {
        // Quotes escape as \" and \n as \\n inside JSON.stringify; non-ASCII
        // hashes as UTF-8 — pinned against the node hash of this fixture.
        let u = AllergenRecipe(
            slug: "uni", name: "U",
            ingredients: [.init(item: "Jalapeño \"hot\""), .init(item: "Crème\nfraîche")])
        XCTAssertEqual(
            AllergenAttestationCompute.computeRecipeFingerprint(slug: "uni", recipes: [u]),
            "6c3feadefb6638e79bff6cfa9d44f2abe996b76241640fe057f863e91ae27e93")
    }

    // ── normalizeAllergens ──────────────────────────────────────────────

    func testNormalizeAllergensTrimsLowercasesDedupesSorts() {
        XCTAssertEqual(
            AllergenAttestationCompute.normalizeAllergens(["Milk", "fish", "wheat", "milk "]),
            ["fish", "milk", "wheat"])
    }

    func testNormalizeAllergensClipsTo64AndDropsEmpties() {
        let long = String(repeating: "x", count: 80)
        let result = AllergenAttestationCompute.normalizeAllergens([long, "", "   "])
        XCTAssertEqual(result.count, 1)
        XCTAssertEqual(result[0].count, 64)
    }

    // ── parseAllergensJson ──────────────────────────────────────────────

    func testParseAllergensJson() {
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson(#"["fish","milk"]"#), ["fish", "milk"])
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson("junk"), [])
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson(#"{"not":"array"}"#), [])
        XCTAssertEqual(AllergenAttestationCompute.parseAllergensJson(#"["a",1,null,"b"]"#), ["a", "b"])
    }

    // ── status ──────────────────────────────────────────────────────────

    private func record(fingerprint: String) -> AllergenAttestationRecord {
        AllergenAttestationRecord(
            id: 1, recipeSlug: "queso", locationId: "default",
            allergensJson: "[]", recipeFingerprint: fingerprint,
            attestedBy: "Dana", note: nil, createdAt: "2026-07-02 10:00:00")
    }

    func testStatusUnattestedWithoutRow() {
        XCTAssertEqual(AllergenAttestationCompute.status(latest: nil, currentFingerprint: "abc"), .unattested)
    }

    func testStatusAttestedWhenFingerprintMatches() {
        XCTAssertEqual(
            AllergenAttestationCompute.status(latest: record(fingerprint: "abc"), currentFingerprint: "abc"),
            .attested)
    }

    func testStatusStaleWhenFingerprintDiffersOrRecipeGone() {
        XCTAssertEqual(
            AllergenAttestationCompute.status(latest: record(fingerprint: "abc"), currentFingerprint: "def"),
            .stale)
        // Recipe removed from the cache → current fingerprint nil → stale,
        // NEVER attested (fail-safe direction).
        XCTAssertEqual(
            AllergenAttestationCompute.status(latest: record(fingerprint: "abc"), currentFingerprint: nil),
            .stale)
    }
}
